"""
Django settings for snorkelmap project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')
SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

AUTH_USER_MODEL = 'snorkelusers.User'

EMAIL_BACKEND = 'django_ses.SESBackend'
DEFAULT_FROM_EMAIL = "SnorkelMap <noreply@snorkelmap.com>"
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_SES_REGION_NAME = 'eu-north-1'
AWS_SES_REGION_ENDPOINT = f'email.{AWS_SES_REGION_NAME}.amazonaws.com'
MAPBOX_TOKEN = os.environ.get("MAPBOX_TOKEN")

# Used for requests Django makes itself: the reverse geocode behind a
# listing's address, and the raster map drawn for each location.
# Separate from MAPBOX_TOKEN with no fallback, because that one is
# meant to be restricted to the site's own URLs and a request from the
# server carries no referring page, so a restricted token fails here
# and nowhere else. Sharing one token means either the public token is
# unrestricted, or the server quietly stops working.
MAPBOX_SERVER_TOKEN = os.environ.get("MAPBOX_SERVER_TOKEN", "")

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
]

# Application definition

INSTALLED_APPS = [
    "django.forms",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'storages',
    'django_ses',
    'allauth',
    'allauth.account',
    'turnstile',
    'snorkelusers',
    'snorkel_locations',
    'snorkel_reviews',
    'snorkel_visibility',
    'locations_snorkelled',
    'saved_locations',
    'contributions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

ROOT_URLCONF = 'snorkelmap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'snorkelmap.wsgi.application'

#Additional Security Settings
SECURE_BROWSER_XSS_FILTER = True
SRF_COOKIE_SECURE = True
CSRF_USE_SESSIONS = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'Strict'
SECURE_CONTENT_TYPE_NOSNIFF = True

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
        'default': {
            "ENGINE": "django.contrib.gis.db.backends.postgis",
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

FORM_RENDERER = "django.forms.renderers.TemplatesSetting"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-allauth config
ACCOUNT_ADAPTER = 'snorkelusers.adapters.CustomAccountAdapter'
SITE_ID = 1
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_SIGNUP_FIELDS = ['first_name', 'email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_SUBJECT_PREFIX = 'SnorkelMap.com -'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_LOGIN_METHODS = ['username']
ACCOUNT_LOGOUT_ON_GET = True

ACCOUNT_FORMS = {
    'signup': 'snorkelusers.forms.CustomSignupForm',
    'login': 'snorkelusers.forms.CustomLoginForm',
}

# ── R2 media bucket ──────────────────────────────────────────────────
# Photographs submitted with a location. Separate from the static files
# bucket: different lifecycle, different access pattern, and a
# different bucket per environment so development uploads never land
# beside real ones. Every value comes from the environment, so the same
# code path runs everywhere and only the .env differs.
R2_ENDPOINT_URL = os.environ.get('R2_ENDPOINT_URL')
R2_ACCESS_KEY = os.environ.get('R2_ACCESS_KEY')
R2_SECRET_KEY = os.environ.get('R2_SECRET_KEY')
R2_MEDIA_BUCKET = os.environ.get('R2_MEDIA_BUCKET', '')

# Required, and deliberately separate from the static files pair above.
# There is no fallback between them: this token signs uploads, so it is
# scoped to the media bucket alone. Sharing one token would also make a
# misconfiguration invisible, because signing succeeds without any
# permission check and the failure only shows up as uploads that are
# refused and objects that appear not to exist.
R2_MEDIA_ACCESS_KEY = os.environ.get('R2_MEDIA_ACCESS_KEY', '')
R2_MEDIA_SECRET_KEY = os.environ.get('R2_MEDIA_SECRET_KEY', '')

# Custom domain in front of the bucket. Cloudflare Image
# Transformations are served from the same host, so this is also the
# base for /cdn-cgi/image/ URLs.
R2_MEDIA_PUBLIC_BASE = os.environ.get('R2_MEDIA_PUBLIC_BASE', '')

# How long an upload slot stays valid. Long enough for a large photo on
# a poor connection, short enough that a signature copied out of the
# network tab is not much use later.
R2_MEDIA_UPLOAD_EXPIRY = int(os.environ.get('R2_MEDIA_UPLOAD_EXPIRY', '900'))

# "post" signs a form upload carrying a content-length-range condition,
# which lets the bucket refuse an oversized body outright. Set to "put"
# if R2 declines POST object uploads on this account; the size is then
# caught during verification instead.
R2_MEDIA_UPLOAD_METHOD = os.environ.get('R2_MEDIA_UPLOAD_METHOD', 'post')

# Shared with the Worker that relays bucket events. Requests to the
# media webhook are signed with it.
R2_MEDIA_WEBHOOK_SECRET = os.environ.get('R2_MEDIA_WEBHOOK_SECRET', '')


# ── Map data bucket ──────────────────────────────────────────────────
# A third bucket, separate again from static files and photographs. It
# holds one small file listing every published location, rewritten when
# a location goes live and read by every visitor who opens the map.
#
# The file is written under a content addressed name and served
# immutable, because a browser's cache cannot be purged: Cloudflare's
# can, but anyone who already holds the file keeps it until its max-age
# expires. A new name for new contents avoids that entirely.
R2_GEO_BUCKET = os.environ.get('R2_GEO_BUCKET', '')

# Scoped to the geo bucket alone, with no fallback to either other
# pair, for the same reason the media credentials have none.
R2_GEO_ACCESS_KEY = os.environ.get('R2_GEO_ACCESS_KEY', '')
R2_GEO_SECRET_KEY = os.environ.get('R2_GEO_SECRET_KEY', '')

# Custom domain in front of the bucket. The browser fetches the data
# file from here, which is a different origin from the site, so the
# bucket needs a CORS policy allowing GET from the site's origins or
# the request fails in the page while succeeding in the address bar.
R2_GEO_PUBLIC_BASE = os.environ.get('R2_GEO_PUBLIC_BASE', '')

# Shown in place of a missing thumbnail, anywhere in the project.
NO_IMAGE_URL = os.environ.get(
    'NO_IMAGE_URL',
    'https://mstatic.snorkelmap.com/images/no_image_for_location.png')

# How many cards the pane asks for. Fewer on a phone, where the request
# is likely to be on mobile data and fewer fit on screen anyway.
MAP_PANE_LIMIT = 20
MAP_PANE_LIMIT_MOBILE = 12


# ── what3words ───────────────────────────────────────────────────────
# Looked up inline when a location is created, with a three second
# timeout, and skipped without complaint on any failure. A listing does
# not depend on having a three word address, and no address is worth
# making somebody wait on a publish screen for.
W3W_API_KEY = os.environ.get('W3W_API_KEY', '')


# ── logging ──────────────────────────────────────────────────────────
# Django's built-in default only prints request tracebacks to console
# when DEBUG=True. In production (DEBUG=False) with no LOGGING config,
# an unhandled exception is caught, a generic 500 page is served, and
# the traceback goes nowhere - not to console, not anywhere else. This
# forces it to stdout regardless of DEBUG, so `docker logs` picks it up.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
