# Generated by Django 6.0.2 on 2026-07-19 11:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('media_type', models.PositiveSmallIntegerField(choices=[(1, 'Image'), (2, 'Video')])),
                ('media_category', models.PositiveSmallIntegerField(choices=[(1, 'Underwater'), (2, 'Surface')])),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('object_key', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending upload'), (1, 'Active'), (2, 'Removed')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orignal_media_meta', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'location media',
            },
        ),
        migrations.CreateModel(
            name='LocationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('alternate_names', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('entry_description', models.TextField(blank=True, default='')),
                ('access_type', models.JSONField(blank=True, default=list)),
                ('water_type', models.JSONField(blank=True, default=list)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Difficult'), (4, 'Extreme')], default=1)),
                ('environment_types', models.JSONField(blank=True, default=dict)),
                ('marine_life', models.JSONField(blank=True, default=dict)),
                ('hazards', models.JSONField(blank=True, default=dict)),
                ('facilities', models.JSONField(blank=True, default=dict)),
                ('marker_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision_comment', models.CharField(blank=True, default='', max_length=255)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_revisions', to=settings.AUTH_USER_MODEL)),
                ('featured_surface_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snorkel_locations.locationmedia')),
                ('featured_underwater_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snorkel_locations.locationmedia')),
            ],
            options={
                'ordering': ['-increment'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=300)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='snorkel_locations.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locales', to='snorkel_locations.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SnorkelLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=400, unique=True)),
                ('lat_long', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('w3w', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Hidden'), (3, 'Removed')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.JSONField(blank=True, null=True)),
                ('notices', models.JSONField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='snorkel_locations.country')),
                ('current_revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for', to='snorkel_locations.locationrevision')),
                ('locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='snorkel_locations.locale')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='snorkel_locations.region')),
            ],
        ),
        migrations.AddField(
            model_name='locationrevision',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='snorkel_locations.snorkellocation'),
        ),
        migrations.AddField(
            model_name='locationmedia',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='snorkel_locations.snorkellocation'),
        ),
        migrations.AddIndex(
            model_name='snorkellocation',
            index=models.Index(fields=['country', 'region', 'locale'], name='snorkel_loc_country_94adcb_idx'),
        ),
        migrations.AddIndex(
            model_name='locationrevision',
            index=models.Index(fields=['location', '-increment'], name='snorkel_loc_locatio_11c2e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationrevision',
            constraint=models.UniqueConstraint(fields=('location', 'increment'), name='unique_increment_per_location'),
        ),
    ]
