# Generated by Django 6.0.2 on 2026-09-12 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snorkel_locations', '0006_location_map_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisibilityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_reports', models.PositiveIntegerField(default=0)),
                ('average_visibility', models.FloatField(blank=True, null=True)),
                ('last_report_at', models.DateTimeField(blank=True, null=True)),
                ('ai_comment', models.TextField(blank=True, default='')),
                ('ai_comment_updated_at', models.DateTimeField(blank=True, null=True)),
                ('snorkel_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visibility', to='snorkel_locations.snorkellocation')),
            ],
        ),
        migrations.CreateModel(
            name='VisibilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('observed_at', models.DateTimeField()),
                ('user_comment', models.TextField(blank=True, default='')),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='snorkel_visibility.visibilitylocation')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visibility_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['location', '-observed_at'], name='snorkel_vis_locatio_75f4c9_idx')],
            },
        ),
    ]
